blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/zhoucq/mysql-exporter/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/zhoucq/mysql-exporter/security/advisories
    about: Please report security vulnerabilities here.